### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by JSimo** [datasektionen/hodis#2]
Feature request:

Would be nice if the `/users/<name>` api gets som friendly CORS headers on it. Such that one can use it in other clients located on `*.datasektionen.se`.

**Comment by addreas** [comment]
Unless something is broken it should already have `Header("Access-Control-Allow-Origin", "*")`. Are there any others that should be set?

**Comment by JSimo** [comment]
My bad, I were using `http://hodis.datasektionen.se` which means that I'm hitting the redirect to https and not the wanted endpoint. Getting the data I wanted now :D 

Ty for quick response 👍
